services:
  jekyll:
    build: .
    container_name: blog-endangereditems-com
    command: jekyll serve --host 0.0.0.0
    ports:
      - 4001:4000
    volumes:
      - ./:/srv/jekyll
    restart: unless-stopped
